on: [push]

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: We test it locally with act
    steps:
      - name: Action
        uses: ./ # Uses an action in the root directory
        id: pokemon
        with:
          pokemon_id: 150
      - name: Get Action
        run: echo "${GITHUB_WORKFLOW}:${GITHUB_ACTION}"
